name: Activity Types Workflow
# run-name: Activity Types

on: 
  issues:
    types: opened

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:    
    - name: Deploy application
      run: echo "Deploying application..."
  
