name: Sample Workflow

on: [workflow_dispatch, push]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v5
    - name: Install dependencies
      run: npm install
    - name: Build application
      run: npm run build
    - name: Get IP
      run: ifconfig
    - name: Deploy application
      run: npm start
