name: Sample Workflow

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: clone_repository
      uses: actions/checkout@v5
    - name: install_dependencies
      run: npm install
    - name: build
      run: npm run build
    - name: upload_artifact
      uses: actions/upload-artifact@v5
      with:
        name: test
        path: README.md
