name: Matrix WF
run-name: Matrix WF
on: push
jobs:
  job1:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-15']
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
    - name: step1
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
