name: Outputs WF

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      id: abc
      run: echo "student_name=Ajay" >> $GITHUB_OUTPUT
    - name: step2
      id: def
      run: echo "My name is ${{ steps.abc.outputs.student_name }}"
