name: Secrets WF
run-name: Secrets WF
on: workflow_dispatch
env:
  MY_SECRET_NAME: ${{ secrets.NAME }}
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: My Secret Step
      run: echo $MY_SECRET_NAME
      
    - name: Checkout
      uses: actions/checkout@v4

#    - name: Start tmate session
#      uses: mxschmitt/action-tmate@v3
#      with:
#        ssh-key: false
#        wait: true

    - name: Start Upterm Session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
        wait-timeout-minutes: 120
