name: Variables demo
run-name: Variables demo
on: push
env:
  NAME: Ajay
  VAR_REP_NAME: ${{ vars.REP_VAR }}
  SEC_REP_NAME: ${{ secrets.REP_SECRET }}
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - name: step1
      run: echo "The name is - ${{ env.NAME }}"
    - name: step2
      run: echo "This value is from repo - ${{ env.VAR_REP_NAME }}"
    - name: step3
      run: echo "SEC_REP_NAME = ${{ env.SEC_REP_NAME }}" >> /tmp/secrets.txt
    - name: step4
      run: cat /tmp/secrets.txt
    - name: step5
      run: echo "SEC_REP_NAME = ${{ env.SEC_REP_NAME }}" | base64
    - name: step6
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
        wait-timeout-minutes: 5
