name: Variables demo
run-name: Variables demo
on: workflow_dispatch
env:
  NAME: Ajay
jobs:
  job1:
    env:
      NAME: Naidu
    runs-on: ubuntu-latest
    steps:
    - name: step1
      env:
        NAME: ${{ env.NAME }}-job
      run: echo "This value is from step - ${{ env.NAME }}"
    - name: step2
      run: echo "This value is from job - $NAME"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "This value is from WF - $NAME"
