name: Variables demo
run-name: Variables demo
on: push
env:
  NAME: Ajay
  VAR_REP_NAME: ${{ vars.REP_VAR }}
  SEC_REP_NAME: ${{ secrets.REP_SECRET }}
jobs:
  job1:
    runs-on: naidu
    environment: PROD
    steps:
    - name: step1
      run: echo "The name is - ${{ env.NAME }}"
    - name: step2
      run: echo "This value is from repo - ${{ env.VAR_REP_NAME }}"
    - name: step3
      run: env
